### PR TITLE
[FIX README] The routeDidChange event is fired on the router

### PR DESCRIPTION
**Pull request by balinterdi**

### CODE REVIEW

**Comment by mansona** [comment]
I just came across this issue 🙈 it would be great if we could get this merged so that other people aren't hitting the wrong documentation

**Comment by balinterdi** [comment]
@chrismllr Any chance of getting this merged in? Thank you.

**Comment by chrismllr** [comment]
@balinterdi I'm not a maintainer on this project, I believe you'll need a @poteto or @mike-north for approval and merge.

**Comment by balinterdi** [comment]
Oops, sorry, I just saw that you contributed quite a bit recently.

**Comment by barryofguilder** [comment]
I just spent a bunch of cycles trying to figure this one out and was pointed to this. Would love to see this merged so others don't hit this like I just did.

**Comment by balinterdi** [comment]
@poteto As it seems to trip up people, could you click the merge button? (It's just a README change so a new release need not be made.)

**Comment by balinterdi** [comment]
Thanks!

**Comment by sukima** [comment]
When did this change? It doesn't work on Ember 3.4: https://ember-twiddle.com/9b001747724d6cf6c4be7d8899d11bbf

**Pull request merged**
